spring:
  profiles:
    active: dev

# job.name이 넘어오면 해당 값이 일치하는 job만 실행
# java -jar batch-application.jar --job.name=simpleJob
spring.batch.job.names: ${job.name:NONE}

---

spring:
  profiles: dev
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1
      username: sa
      password:
      driver-class-name: org.h2.Driver


---

spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: admin
      password: admin
      driver-class-name: com.mysql.jdbc.Driver